def show_menu():
    print("*" * 30)
    print()
    print("欢迎使用黑马名片管理系统")
    print()
    print("*" * 30)
    print()
    print("  1. 新建名片")
    print("  2. 显示全部")
    print("  3. 查询名片")
    print("  0. 退出系统")
    print()
    print("*" * 30)
